// source: src/utils/pay_for_blob.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide("proto.MsgPayForBlobs")

goog.require("jspb.BinaryReader")
goog.require("jspb.BinaryWriter")
goog.require("jspb.Message")

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MsgPayForBlobs = function (opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, proto.MsgPayForBlobs.repeatedFields_, null)
}
goog.inherits(proto.MsgPayForBlobs, jspb.Message)
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.MsgPayForBlobs.displayName = "proto.MsgPayForBlobs"
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.MsgPayForBlobs.repeatedFields_ = [2, 3, 4, 8]

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.MsgPayForBlobs.prototype.toObject = function (opt_includeInstance) {
		return proto.MsgPayForBlobs.toObject(opt_includeInstance, this)
	}

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.MsgPayForBlobs} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.MsgPayForBlobs.toObject = function (includeInstance, msg) {
		var f,
			obj = {
				signer: jspb.Message.getFieldWithDefault(msg, 1, ""),
				namespacesList: msg.getNamespacesList_asB64(),
				blobSizesList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
				shareCommitmentsList: msg.getShareCommitmentsList_asB64(),
				shareVersionsList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
			}

		if (includeInstance) {
			obj.$jspbMessageInstance = msg
		}
		return obj
	}
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MsgPayForBlobs}
 */
proto.MsgPayForBlobs.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes)
	var msg = new proto.MsgPayForBlobs()
	return proto.MsgPayForBlobs.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MsgPayForBlobs} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MsgPayForBlobs}
 */
proto.MsgPayForBlobs.deserializeBinaryFromReader = function (msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break
		}
		var field = reader.getFieldNumber()
		switch (field) {
			case 1:
				var value = /** @type {string} */ (reader.readString())
				msg.setSigner(value)
				break
			case 2:
				var value = /** @type {!Uint8Array} */ (reader.readBytes())
				msg.addNamespaces(value)
				break
			case 3:
				var value = /** @type {!Array<number>} */ (reader.readPackedUint32())
				msg.setBlobSizesList(value)
				break
			case 4:
				var value = /** @type {!Uint8Array} */ (reader.readBytes())
				msg.addShareCommitments(value)
				break
			case 8:
				var value = /** @type {!Array<number>} */ (reader.readPackedUint32())
				msg.setShareVersionsList(value)
				break
			default:
				reader.skipField()
				break
		}
	}
	return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MsgPayForBlobs.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter()
	proto.MsgPayForBlobs.serializeBinaryToWriter(this, writer)
	return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MsgPayForBlobs} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MsgPayForBlobs.serializeBinaryToWriter = function (message, writer) {
	var f = undefined
	f = message.getSigner()
	if (f.length > 0) {
		writer.writeString(1, f)
	}
	f = message.getNamespacesList_asU8()
	if (f.length > 0) {
		writer.writeRepeatedBytes(2, f)
	}
	f = message.getBlobSizesList()
	if (f.length > 0) {
		writer.writePackedUint32(3, f)
	}
	f = message.getShareCommitmentsList_asU8()
	if (f.length > 0) {
		writer.writeRepeatedBytes(4, f)
	}
	f = message.getShareVersionsList()
	if (f.length > 0) {
		writer.writePackedUint32(8, f)
	}
}

/**
 * optional string signer = 1;
 * @return {string}
 */
proto.MsgPayForBlobs.prototype.getSigner = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""))
}

/**
 * @param {string} value
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.setSigner = function (value) {
	return jspb.Message.setProto3StringField(this, 1, value)
}

/**
 * repeated bytes namespaces = 2;
 * @return {!Array<string>}
 */
proto.MsgPayForBlobs.prototype.getNamespacesList = function () {
	return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 2))
}

/**
 * repeated bytes namespaces = 2;
 * This is a type-conversion wrapper around `getNamespacesList()`
 * @return {!Array<string>}
 */
proto.MsgPayForBlobs.prototype.getNamespacesList_asB64 = function () {
	return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(this.getNamespacesList()))
}

/**
 * repeated bytes namespaces = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNamespacesList()`
 * @return {!Array<!Uint8Array>}
 */
proto.MsgPayForBlobs.prototype.getNamespacesList_asU8 = function () {
	return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(this.getNamespacesList()))
}

/**
 * @param {!(Array<!Uint8Array>|Array<string>)} value
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.setNamespacesList = function (value) {
	return jspb.Message.setField(this, 2, value || [])
}

/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.addNamespaces = function (value, opt_index) {
	return jspb.Message.addToRepeatedField(this, 2, value, opt_index)
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.clearNamespacesList = function () {
	return this.setNamespacesList([])
}

/**
 * repeated uint32 blob_sizes = 3;
 * @return {!Array<number>}
 */
proto.MsgPayForBlobs.prototype.getBlobSizesList = function () {
	return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 3))
}

/**
 * @param {!Array<number>} value
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.setBlobSizesList = function (value) {
	return jspb.Message.setField(this, 3, value || [])
}

/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.addBlobSizes = function (value, opt_index) {
	return jspb.Message.addToRepeatedField(this, 3, value, opt_index)
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.clearBlobSizesList = function () {
	return this.setBlobSizesList([])
}

/**
 * repeated bytes share_commitments = 4;
 * @return {!Array<string>}
 */
proto.MsgPayForBlobs.prototype.getShareCommitmentsList = function () {
	return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 4))
}

/**
 * repeated bytes share_commitments = 4;
 * This is a type-conversion wrapper around `getShareCommitmentsList()`
 * @return {!Array<string>}
 */
proto.MsgPayForBlobs.prototype.getShareCommitmentsList_asB64 = function () {
	return /** @type {!Array<string>} */ (jspb.Message.bytesListAsB64(this.getShareCommitmentsList()))
}

/**
 * repeated bytes share_commitments = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getShareCommitmentsList()`
 * @return {!Array<!Uint8Array>}
 */
proto.MsgPayForBlobs.prototype.getShareCommitmentsList_asU8 = function () {
	return /** @type {!Array<!Uint8Array>} */ (jspb.Message.bytesListAsU8(this.getShareCommitmentsList()))
}

/**
 * @param {!(Array<!Uint8Array>|Array<string>)} value
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.setShareCommitmentsList = function (value) {
	return jspb.Message.setField(this, 4, value || [])
}

/**
 * @param {!(string|Uint8Array)} value
 * @param {number=} opt_index
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.addShareCommitments = function (value, opt_index) {
	return jspb.Message.addToRepeatedField(this, 4, value, opt_index)
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.clearShareCommitmentsList = function () {
	return this.setShareCommitmentsList([])
}

/**
 * repeated uint32 share_versions = 8;
 * @return {!Array<number>}
 */
proto.MsgPayForBlobs.prototype.getShareVersionsList = function () {
	return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 8))
}

/**
 * @param {!Array<number>} value
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.setShareVersionsList = function (value) {
	return jspb.Message.setField(this, 8, value || [])
}

/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.addShareVersions = function (value, opt_index) {
	return jspb.Message.addToRepeatedField(this, 8, value, opt_index)
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.MsgPayForBlobs} returns this
 */
proto.MsgPayForBlobs.prototype.clearShareVersionsList = function () {
	return this.setShareVersionsList([])
}
