// source: src/utils/pay_for_blob.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide("proto.Blob")

goog.require("jspb.BinaryReader")
goog.require("jspb.BinaryWriter")
goog.require("jspb.Message")

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Blob = function (opt_data) {
	jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.Blob, jspb.Message)
if (goog.DEBUG && !COMPILED) {
	/**
	 * @public
	 * @override
	 */
	proto.Blob.displayName = "proto.Blob"
}

if (jspb.Message.GENERATE_TO_OBJECT) {
	/**
	 * Creates an object representation of this proto.
	 * Field names that are reserved in JavaScript and will be renamed to pb_name.
	 * Optional fields that are not set will be set to undefined.
	 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
	 * For the list of reserved names please see:
	 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
	 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
	 *     JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @return {!Object}
	 */
	proto.Blob.prototype.toObject = function (opt_includeInstance) {
		return proto.Blob.toObject(opt_includeInstance, this)
	}

	/**
	 * Static version of the {@see toObject} method.
	 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
	 *     the JSPB instance for transitional soy proto support:
	 *     http://goto/soy-param-migration
	 * @param {!proto.Blob} msg The msg instance to transform.
	 * @return {!Object}
	 * @suppress {unusedLocalVariables} f is only used for nested messages
	 */
	proto.Blob.toObject = function (includeInstance, msg) {
		var f,
			obj = {
				namespaceId: msg.getNamespaceId_asB64(),
				data: msg.getData_asB64(),
				shareVersion: jspb.Message.getFieldWithDefault(msg, 3, 0),
				namespaceVersion: jspb.Message.getFieldWithDefault(msg, 4, 0),
			}

		if (includeInstance) {
			obj.$jspbMessageInstance = msg
		}
		return obj
	}
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Blob}
 */
proto.Blob.deserializeBinary = function (bytes) {
	var reader = new jspb.BinaryReader(bytes)
	var msg = new proto.Blob()
	return proto.Blob.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Blob} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Blob}
 */
proto.Blob.deserializeBinaryFromReader = function (msg, reader) {
	while (reader.nextField()) {
		if (reader.isEndGroup()) {
			break
		}
		var field = reader.getFieldNumber()
		switch (field) {
			case 1:
				var value = /** @type {!Uint8Array} */ (reader.readBytes())
				msg.setNamespaceId(value)
				break
			case 2:
				var value = /** @type {!Uint8Array} */ (reader.readBytes())
				msg.setData(value)
				break
			case 3:
				var value = /** @type {number} */ (reader.readUint32())
				msg.setShareVersion(value)
				break
			case 4:
				var value = /** @type {number} */ (reader.readUint32())
				msg.setNamespaceVersion(value)
				break
			default:
				reader.skipField()
				break
		}
	}
	return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Blob.prototype.serializeBinary = function () {
	var writer = new jspb.BinaryWriter()
	proto.Blob.serializeBinaryToWriter(this, writer)
	return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Blob} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Blob.serializeBinaryToWriter = function (message, writer) {
	var f = undefined
	f = message.getNamespaceId_asU8()
	if (f.length > 0) {
		writer.writeBytes(1, f)
	}
	f = message.getData_asU8()
	if (f.length > 0) {
		writer.writeBytes(2, f)
	}
	f = message.getShareVersion()
	if (f !== 0) {
		writer.writeUint32(3, f)
	}
	f = message.getNamespaceVersion()
	if (f !== 0) {
		writer.writeUint32(4, f)
	}
}

/**
 * optional bytes namespace_id = 1;
 * @return {string}
 */
proto.Blob.prototype.getNamespaceId = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""))
}

/**
 * optional bytes namespace_id = 1;
 * This is a type-conversion wrapper around `getNamespaceId()`
 * @return {string}
 */
proto.Blob.prototype.getNamespaceId_asB64 = function () {
	return /** @type {string} */ (jspb.Message.bytesAsB64(this.getNamespaceId()))
}

/**
 * optional bytes namespace_id = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getNamespaceId()`
 * @return {!Uint8Array}
 */
proto.Blob.prototype.getNamespaceId_asU8 = function () {
	return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getNamespaceId()))
}

/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.Blob} returns this
 */
proto.Blob.prototype.setNamespaceId = function (value) {
	return jspb.Message.setProto3BytesField(this, 1, value)
}

/**
 * optional bytes data = 2;
 * @return {string}
 */
proto.Blob.prototype.getData = function () {
	return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""))
}

/**
 * optional bytes data = 2;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.Blob.prototype.getData_asB64 = function () {
	return /** @type {string} */ (jspb.Message.bytesAsB64(this.getData()))
}

/**
 * optional bytes data = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.Blob.prototype.getData_asU8 = function () {
	return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(this.getData()))
}

/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.Blob} returns this
 */
proto.Blob.prototype.setData = function (value) {
	return jspb.Message.setProto3BytesField(this, 2, value)
}

/**
 * optional uint32 share_version = 3;
 * @return {number}
 */
proto.Blob.prototype.getShareVersion = function () {
	return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0))
}

/**
 * @param {number} value
 * @return {!proto.Blob} returns this
 */
proto.Blob.prototype.setShareVersion = function (value) {
	return jspb.Message.setProto3IntField(this, 3, value)
}

/**
 * optional uint32 namespace_version = 4;
 * @return {number}
 */
proto.Blob.prototype.getNamespaceVersion = function () {
	return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0))
}

/**
 * @param {number} value
 * @return {!proto.Blob} returns this
 */
proto.Blob.prototype.setNamespaceVersion = function (value) {
	return jspb.Message.setProto3IntField(this, 4, value)
}
