export const IbcChainName = {
	"injective-1": "Injective",
	"neutron-1": "Neutron",
	"osmosis-1": "Osmosis",
	"stride-1": "Stride",
	"dymension_1100-1": "Dymension",
	"stargaze-1": "Stargaze",
	"elys-1": "Elys",
	"secret-4": "Secret",
	"umee-1": "Umee",
	"pryzm-1": "Pryzm",
	"archway-1": "Archway",
	"kyve-1": "Kyve",
	"coreum-mainnet-1": "Coreum",
	"quicksilver-2": "Quicksilver",
	"jackal-1": "Jackal",
}

export const IbcChainLogo = {
	_unknown: "/img/chains/unknown.png",
	_celestia: "/img/chains/celestia.png",
	"injective-1": "/img/chains/injective.png",
	"neutron-1": "/img/chains/neutron.png",
	"osmosis-1": "/img/chains/osmosis.png",
	"stride-1": "/img/chains/stride.png",
	"dymension_1100-1": "/img/chains/dymension.png",
	"stargaze-1": "/img/chains/stargaze.png",
	"elys-1": "/img/chains/elys.png",
	"secret-4": "/img/chains/secret.png",
	"umee-1": "/img/chains/umee.png",
	"pryzm-1": "/img/chains/pryzm.png",
	"archway-1": "/img/chains/archway.png",
	"kyve-1": "/img/chains/kyve.png",
	"coreum-mainnet-1": "/img/chains/coreum.png",
	"quicksilver-2": "/img/chains/quicksilver.png",
	"jackal-1": "/img/chains/jackal.png",
}
